[msg MSG_000 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 6 -1 1][f 3 1 1 0 0 1]Owww...[n][f 1 3 -1][f 1 1][e]

[msg MSG_001 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 2]Is this...?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 2 -1 1][f 3 1 1 0 0 3]Look, this is the same place as last time![n]So they are connected from place to place![n][f 1 3 -1][f 1 1][e]

[msg MSG_002 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 5 0 1][f 3 1 1 0 0 4]Y-You guys... Why'd you come back...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_003 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 3 0 1][f 3 1 1 0 0 5]I get it! You're the ones behind this![n][f 1 3 -1][f 1 1][e]

[msg MSG_004 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 5 -1 1][f 3 1 1 0 0 6]You're that thing from last time...![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 8 -1 1][f 3 1 1 0 0 7]Wait, what the hell did you just say!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_005 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 8]Lately, I can tell someone's been[n]throwing people in here.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 10]It's making this world more and more[n]messed up...[n][f 1 3 -1][f 1 1][e]

[msg MSG_006 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 11]This is the second time you guys[n]came here. And I don't think anyone[n]forced you in.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 12]That means you're the most suspicious![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 13][f 4 6 8 3 0 1][f 4 9 8 10 5 10 0]You guys must be the ones throwing the[n]people in here, raaaawr![n][f 1 3 -1][f 1 1][e]

[msg MSG_007 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 14]"Rawr" my ass!![n][f 1 3 -1][f 1 1][e]

[msg MSG_008 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 15]What're you talking about, "throwing[n]people in!?"[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 16]If someone was thrown in here and they[n]couldn't get out, they might die![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 17]Who would do such a--[n][f 1 3 -1][f 1 1][e]

[msg MSG_009 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 8 -1 1][f 3 1 1 0 0 18]Wait a sec...[n][f 1 3 -1][f 1 1][e]

[msg MSG_010 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 19]All this talk about someone throwing[n]people in here...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 8 -1 1][f 3 1 1 0 0 20]Does he mean Senpai and the announcer?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 21]Did that "someone" throw those two[n]in here?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 22][f 4 9 2 3 5 0 5]H-Hey... What do you think?[n][f 1 3 -1][f 1 1][e]

[sel SEL_011]
[f 0 5 -258][f 2 1]"That must be it."[e]
[f 0 5 -258][f 2 1]"They accidentally fell in."[e]
[f 0 5 -258][f 2 1]"I don't know."[e]

[msg MSG_012 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 23]Yeah... I agree.[n][f 1 3 -1][f 1 1][e]

[msg MSG_013 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 24]So the other two might've tried touching[n]the TV screen, like you did, and fell[n]in by accident?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 25]Well... That actually happened to us,[n]so we can't completely rule it out...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 26]But doesn't it bug you how this[n]bear keeps saying someone's been[n]throwing people in here?[n][f 1 3 -1][f 1 1][e]

[msg MSG_014 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 27]I can't say for sure either...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 28]But doesn't it bug you how this[n]bear keeps saying someone's been[n]throwing people in here?[n][f 1 3 -1][f 1 1][e]

[msg MSG_015 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 29]Let's assume he's telling the truth...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 8 -1 1][f 3 1 1 0 0 30]Could it be that someone's throwing[n]people in here, intending to kill them...?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 31]If that's the case...[n][f 1 3 -1][f 1 1][e]

[msg MSG_016 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 3 0 1][f 3 1 1 0 0 32]What're you guys mumbling about?[n]Why'd you come here, anyways!?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 33]It's a one-way door! You can't get out[n]once you're in![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 9 8 3 5 0 5][f 3 1 1 0 0 34]Remember? How I had to let you guys out?[n][f 1 3 -1][f 1 1][e]

[msg MSG_017 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 35]Yeah, whatever.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 36][f 4 6 2 2 -1 1][f 4 9 2 21 5 22 5]We don't need your help this time![n]See, this time we have a lifeli--[n][f 1 3 -1][f 1 1][e]

[msg MSG_018 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 8 -1 1][f 3 1 1 0 0 37]Whaaaaat!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_019 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 38]H-Hey! You better let us out once we're[n]done investigating here![n][f 1 3 -1][f 1 1][e]

[msg MSG_020 [[x 0x94 0x9F][x 0x81 0x8C][x 0x81 0xC0][x 0x81 0xEF]]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0][x 0x8D 0xEA][x 0x8C 0xF7][x 0x81 0x88][x 0x8C 0xF0][x 0x90 0xE5][x 0x81 0xC0][x 0x81 0xEF][x 0x82 0x89][n][f 1 3 -1][f 1 1][e]

[msg MSG_021 [[x 0x85 0xB7][x 0x90 0xFD][x 0x99 0xA6][x 0x85 0xD1] ]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 0][x 0x8C 0xF0][x 0x90 0xE5][x 0x81 0x81][x 0x81 0x84][x 0x82 0x9D][n][f 1 3 -1][f 1 1][e]

[msg MSG_022 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 3 0 1][f 3 1 1 0 0 39]Grrrrr! I'm the one who wants to[n]investigate![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 40]I've lived here for a long time. But it's[n]never been noisy like this till now.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 9 8 3 5 0 5][f 3 1 1 0 0 41]Do you have proof!? Prove to me you're[n]not throwing people in here![n][f 1 3 -1][f 1 1][e]

[msg MSG_023 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 5 -1 1][f 3 1 1 0 0 42]Wha--P-Proof!? [n][f 1 3 -1][f 1 1][e]

[msg MSG_024 [[x 0x85 0xB7][x 0x90 0xFD][x 0x99 0xA6][x 0x85 0xD1] ]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 0][x 0x80 0xF5][x 0x81 0xA5][x 0x82 0x88][x 0x8E 0xA3][x 0x87 0xED][x 0x81 0x81][x 0x81 0x84][x 0x89 0xD5][x 0x81 0xAD][x 0x81 0xAA][x 0x81 0xA9][x 0x81 0x86][x 0x82 0x88][x 0x81 0x8B][x 0x82 0x99][x 0x80 0xEF][x 0x81 0x87][x 0x80 0xF3][x 0x82 0x9D][n][x 0x80 0xE0][x 0x82 0x99][x 0x82 0x88][x 0x81 0x81][x 0x80 0xFD][x 0x80 0xED][x 0x82 0x88][x 0x81 0xC0][x 0x81 0xEF][x 0x81 0x81][x 0x80 0xFD][x 0x81 0xC0][x 0x81 0xEF][x 0x80 0xFE][x 0x80 0xFA][x 0x82 0x9D][n][f 1 3 -1][f 1 1][e]

[msg MSG_025 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 43]See! So it is you guys![n][f 1 3 -1][f 1 1][e]

[msg MSG_026 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 44]For the last time, it's not us, so[n]we've got nothing to prove to you![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 45]Hey, you better answer our questions.[n]This isn't like last time, when we came[n]by accident. We're dead serious![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 46][f 4 9 2 3 5 0 5]Listen up, 'cause people have died in[n]our world... Every time the fog appears,[n]a dead body shows up with it.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 47]It has to be related to this place[n]somehow! If you know something, tell us![n][f 1 3 -1][f 1 1][e]

[msg MSG_027 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 48]A dead body? Whenever the fog appears...?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 49][f 4 9 8 3 5 0 5]I know that if it's foggy on your side,[n]the fog lifts here.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 50]It's really dangerous when the fog lifts.[n]That's when the Shadows get violent.[n][f 1 3 -1][f 1 1][e]

[msg MSG_028 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 6 -1 1][f 3 1 1 0 0 52]Huh...? If you get it, then explain it[n]to us, dammit![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 53]If it's foggy on our side, it isn't[n]in here...? Shadows get violent...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_029 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 3 0 1][f 3 1 1 0 0 54]That's why I said to hurry back! It's[n]dangerous when that happens![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 55]Okay, no more questions.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 56]I know you guys did it! You better stop[n]right now![n][f 1 3 -1][f 1 1][e]

[msg MSG_030 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 57]I've told you and told you, we're not[n]the ones doing it![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 8 2 4][f 3 1 1 0 0 58]I've about had it with you... Why the hell[n]won't you listen to what we're saying!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_031 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 4 0 1][f 3 1 1 0 0 59]I-I'm just saying... you might be the[n]culprits.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 60]I'm just making sure...[n][f 1 3 -1][f 1 1][e]

[msg MSG_032 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 9 -1 1][f 3 1 1 0 0 61]What...? Man, this bear's driving me[n]nuts...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 6 -1 1][f 3 1 1 0 0 62]What is this place, anyways? It looks[n]like a TV studio...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 63]Is something being filmed here...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_033 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 8 -1 1][f 3 1 1 0 0 64]H-Hey, don't tell me... Is that weird[n]show being filmed here!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_034 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 65]Weird show? Filmed? What does[n]that mean?[n][f 1 3 -1][f 1 1][e]

[msg MSG_035 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 66]Uh... I'm asking if someone's been[n]filming the people that get thrown[n]in here.[n][f 1 3 -1][f 1 1][e]

[msg MSG_036 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 67]......?[n]I don't get it...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 9 8 3 5 0 5][f 3 1 1 0 0 68]This world has always been like this.[n]No one has ever done that filming[n]thing here.[n][f 1 3 -1][f 1 1][e]

[msg MSG_037 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 8 -1 1][f 3 1 1 0 0 69]What's "always been like this"[n]supposed to mean?[n][f 1 3 -1][f 1 1][e]

[msg MSG_038 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 70]Only me and Shadows are here![n]I told you before![n][f 1 3 -1][f 1 1][e]

[msg MSG_039 [[x 0x85 0xB7][x 0x90 0xFD][x 0x99 0xA6][x 0x85 0xD1] ]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 0][x 0x80 0xF6][x 0x81 0xA1][x 0x80 0xE0][x 0x82 0x88][x 0x85 0x97][x 0x80 0xFD][x 0x80 0xFF][x 0x81 0xA0][x 0x8A 0xF4][x 0x82 0x88][n][x 0x91 0xCE][x 0x80 0xE9][x 0x81 0x89][x 0x89 0xC0][x 0x81 0xA7][x 0x81 0xAA][x 0x81 0x84][x 0x81 0xA9][x 0x81 0x81][x 0x81 0x84][x 0x8C 0xA5][x 0x80 0xE9][x 0x80 0x81][x 0x80 0x9F][n][f 1 3 -1][f 1 1][e]

[msg MSG_040 [[x 0x94 0x9F][x 0x81 0x8C][x 0x81 0xC0][x 0x81 0xEF]]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0][x 0x81 0xC0][x 0x81 0xEF][x 0x81 0x8C][x 0x87 0x9F][x 0x81 0x8C][x 0x80 0xF9][x 0x80 0xE2][x 0x80 0xE9][x 0x81 0xA0][x 0x80 0xF5][x 0x81 0xAA][x 0x81 0x88][x 0x80 0xE2][x 0x81 0xC0][x 0x81 0xEF][x 0x82 0x9D][n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0][x 0x80 0xFB][x 0x81 0xAA][x 0x81 0x89][x 0x82 0x88][x 0x81 0xBE][x 0x81 0xF0][x 0x80 0xFD][x 0x80 0xFF][x 0x82 0x88][x 0x80 0xFB][x 0x81 0xAA][x 0x81 0x99][x 0x81 0x87][x 0x85 0xBB][x 0x81 0x88][x 0x80 0xE2][x 0x80 0xF5][x 0x82 0x88][n][x 0x81 0xBB][x 0x81 0xD9][x 0x81 0xC4][x 0x81 0xC0][x 0x81 0xC6][x 0x81 0xB5][x 0x81 0x8C][x 0x82 0x88][x 0x94 0xD8][x 0x80 0xE9][x 0x81 0x88][x 0x80 0xE2][x 0x81 0xB1][x 0x80 0xF6][x 0x81 0xA1][x 0x81 0x88][x 0x80 0xE2][x 0x81 0x8C][x 0x80 0x9F][n][f 1 3 -1][f 1 1][e]

[msg MSG_041 [[x 0x85 0xB7][x 0x90 0xFD][x 0x99 0xA6][x 0x85 0xD1] ]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 0][x 0x81 0x88][x 0x81 0xB1][x 0x80 0xE9][x 0x82 0x88][x 0x80 0xE2][x 0x80 0xFF][x 0x80 0xE2][x 0x80 0xFF][x 0x81 0xF1][x 0x81 0xBC][x 0x81 0x82][x 0x80 0xED][x 0x81 0xC0][x 0x81 0xEF][x 0x80 0xFE][x 0x82 0x9D][n][f 1 3 -1][f 1 1][e]

[msg MSG_042 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 71]Ugh... We don't know what these Shadow[n]things are! Or what you are either,[n]for that matter![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 72]You keep telling us to prove our[n]innocence, but you're the most[n]suspicious thing here![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 73]Maybe you're the real culprit![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 9 2 3 5 0 5][f 3 1 1 0 0 74]And what's with that stupid costume!?[n]I'd say it's time you showed your face![n][f 1 3 -1][f 1 1][e]

[msg MSG_043 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 5 -1 1][f 3 1 1 0 0 75]Whoa![n][f 1 3 -1][f 1 1][e]

[msg MSG_044 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 8 -1 1][f 3 1 1 0 0 76]Wh-What the hell are you...?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 77]I-It's empty inside...[n][f 1 3 -1][f 1 1][e]

[msg MSG_045 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 4 0 1][f 3 1 1 0 0 78]Me...? The culprit...?[n]I wouldn't do such a thing...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 79]I just live here...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 80]I just want to live here peacefully...[n][f 1 3 -1][f 1 1][e]

[msg MSG_046 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 81]......[n][f 1 3 -1][f 1 1][e]

[msg MSG_047 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 82]Okay. I'll believe that you guys aren't[n]the culprits.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 83]But I want you to find the real guy who[n]did all this. You have to stop him.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 85]Promise me, or else...[n][f 1 3 -1][f 1 1][e]

[msg MSG_048 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 86]I'm not gonna let you guys outta here.[n][f 1 3 -1][f 1 1][e]

[msg MSG_049 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 3 -1 1][f 3 1 1 0 0 87]Y-You little...![n][f 1 3 -1][f 1 1][e]

[msg MSG_050 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 4 0 1][f 3 1 1 0 0 88]This can't keep going on! My home here[n]will be a complete mess![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 89]And then... and then... I...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 90][f 4 9 8 12 5 12 0]Waaah...[n][f 1 3 -1][f 1 1][e]

[msg MSG_051 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 8 -1 1][f 3 1 1 0 0 91]Wh-What're you crying for[n]all of a sudden...?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 9 -1 1][f 3 1 1 0 0 92][f 4 8 2 8]Geez, this thing's really weirding[n]me out...[n][f 1 3 -1][f 1 1][e]

[msg MSG_052]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> The mysterious bear is asking you to[n]find the culprit behind this...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> Someone on the outside is throwing[n]people into this world...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> If the culprit isn't you, he wants[n]you to find the real culprit...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> The mysterious bear seems serious[n]about this...[n][f 1 3 -1][f 1 1][e]

[msg MSG_053 [Igor]]
[f 0 5 -258][f 2 1][f 4 6 33 1 0 1][f 3 1 1 0 0 94]> "It seems you will encounter a misfortune[n]at your destination, and a great mystery[n]will be imposed upon you..."[n][f 1 3 -1][f 1 1][e]

[msg MSG_054]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> Could this be the mystery that will[n]be thrust upon you...?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> What was the "contract" Igor spoke of...?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> Could finding the culprit and solving[n]the case be part of this promise...?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> In any case, since you cannot leave the[n]TV world on your own, there seems to be[n]no other option...[n][f 1 3 -1][f 1 1][e]

[msg MSG_055 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 4 0 1][f 3 1 1 0 0 95]You're the only ones I can ask. Will you[n]promise me...?[n][f 1 3 -1][f 1 1][e]

[sel SEL_056]
[f 0 5 -258][f 2 1]"I promise."[e]
[f 0 5 -258][f 2 1]"We've got no choice..."[e]

[msg MSG_057 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 2 0 1][f 3 1 1 0 0 96]Th-Thank you![n][f 1 3 -1][f 1 1][e]

[msg MSG_058 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 8 -1 1][f 3 1 1 0 0 97]Damn bear... Practically holding a gun[n]to our heads...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 4 -1 1][f 3 1 1 0 0 98]But... it's true that we came here[n]to figure things out. So far, we're[n]completely in the dark.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 99]Look for the culprit, huh...?[n]Bring it on! You got my word, too.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 100][f 4 9 2 27 5 18 5]Might as well introduce ourselves...[n]I'm Yosuke Hanamura, and this is[n]my buddy [f 4 3].[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 101]You got a name?[n][f 1 3 -1][f 1 1][e]

[msg MSG_059 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 102]...Teddie.[n][f 1 3 -1][f 1 1][e]

[msg MSG_060 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 6 -1 1][f 3 1 1 0 0 103]*groan* Figures...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 4 9 2 27 5 18 5][f 3 1 1 0 0 104]But how are we supposed to find the culprit[n]in the first place?[n][f 1 3 -1][f 1 1][e]

[msg MSG_061 [Teddie]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 105]I dunno...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 106]Oh, but I know where the last person[n]came in.[n][f 1 3 -1][f 1 1][e]

[msg MSG_062 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 8 -1 1][f 3 1 1 0 0 107]The last person...?[n]You mean Saki-senpai!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_063 [Teddie]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 108]I mean the person who came in and[n]disappeared last time. I dunno the name.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 109]I'll take you there. You might find clues.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 110]Oh, one thing first. You two should[n]put these on.[n][f 1 3 -1][f 1 1][e]

[msg MSG_064 [[x 0x81 0xC0][x 0x81 0xEF]]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0][x 0x81 0x93][x 0x81 0x93][x 0x81 0x93][x 0x81 0x8C][x 0x81 0x93][x 0x82 0x99][x 0x80 0x81][n][x 0x81 0xA6][x 0x80 0xE4][x 0x81 0xA2][x 0x80 0xED][x 0x80 0xF1][x 0x81 0xAA][x 0x81 0xB0][x 0x8B 0xF7][x 0x80 0xE4][x 0x8C 0xAD][x 0x80 0xEA][x 0x99 0xB3][x 0x80 0xFD][x 0x81 0xC0][x 0x81 0xEF][x 0x80 0x81][n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0][x 0x80 0xF6][x 0x81 0xA1][x 0x80 0xF6][x 0x81 0xA1][x 0x82 0x99][x 0x81 0xB1][x 0x80 0x81][n][f 1 3 -1][f 1 1][e]

[msg MSG_065 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 111]What're these glasses for...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_066 [Teddie]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 114]They'll help you walk through the fog.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 120]...Well, I've been here for a long time.[n]So you can rely on me![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 121]Uh... But I can only show you where the[n]place is. You guys will have to defend[n]yourselves.[n][f 1 3 -1][f 1 1][e]

[msg MSG_067 [[x 0x85 0xB7][x 0x90 0xFD][x 0x99 0xA6][x 0x85 0xD1] ]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 115][x 0x80 0xFB][x 0x81 0x8C][x 0x82 0x9F][x 0x81 0xC8][x 0x81 0xF4][x 0x81 0xDA][x 0x81 0xB7][x 0x80 0x82][x 0x81 0x81][x 0x81 0x84][x 0x81 0x8C][x 0x82 0x88][x 0x85 0xA0][x 0x81 0x88][x 0x81 0xB1][x 0x80 0xFE][x 0x80 0x9F][n][f 1 3 -1][f 1 1][e]

[msg MSG_068 [[x 0x81 0xC0][x 0x81 0xEF]]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 116][x 0x80 0xF1][x 0x81 0x81][x 0x80 0xFF][x 0x81 0x8C][x 0x8F 0xA9][x 0x85 0xE5][x 0x81 0x89][x 0x81 0xB7][x 0x81 0xC5][x 0x81 0xF2][x 0x80 0xED][x 0x82 0x9F][x 0x84 0xC9][x 0x80 0x82][x 0x81 0x8C][x 0x80 0xF1][x 0x81 0x86][x 0x81 0xC0][x 0x81 0xEF][x 0x82 0x89][n][x 0x81 0xBE][x 0x81 0xF0][x 0x81 0xA7][x 0x81 0x89][x 0x81 0xA0][x 0x80 0xE4][x 0x87 0x9F][x 0x81 0x83][x 0x80 0xE2][x 0x81 0x84][x 0x81 0xA9][x 0x82 0x89][n][f 1 3 -1][f 1 1][e]

[msg MSG_069 [[x 0x85 0xB7][x 0x90 0xFD][x 0x99 0xA6][x 0x85 0xD1] ]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 117][x 0x84 0xC9][x 0x81 0x81][x 0x81 0x84][x 0x82 0x9D][x 0x95 0xEE][x 0x98 0x9C][x 0x81 0x89][x 0x8F 0xE7][x 0x98 0xAD][x 0x81 0xB1][x 0x81 0x88][x 0x81 0x81][x 0x81 0x84][x 0x81 0x8B][x 0x80 0xE6][x 0x82 0x9D][n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 118][x 0x80 0xE8][x 0x80 0xE2][x 0x82 0x88][x 0x91 0xA8][x 0x8E 0xAF][x 0x96 0xAA][x 0x81 0x88][x 0x81 0xB1][x 0x80 0xFE][x 0x81 0xAB][x 0x80 0xE4][x 0x81 0x88][x 0x82 0x89][n][x 0x80 0xF3][x 0x81 0x81][x 0x80 0xEB][x 0x82 0x88][x 0x87 0x8A][x 0x81 0x88][x 0x80 0xE2][x 0x81 0x86][x 0x80 0xE9][x 0x81 0x81][x 0x81 0x84][x 0x89 0xD5][x 0x81 0x81][x 0x81 0x84][x 0x81 0x88][x 0x80 0xE9][x 0x81 0x81][x 0x80 0xFD][x 0x80 0xE9][x 0x80 0x9F][n][f 1 3 -1][f 1 1][e]

[msg MSG_070 [[x 0x81 0xC0][x 0x81 0xEF]]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 119][x 0x96 0xB4][x 0x91 0xE9][x 0x81 0x8D][x 0x80 0xE8][x 0x81 0x86][x 0x81 0x88][x 0x80 0xF5][x 0x80 0xE2][x 0x80 0xE9][x 0x81 0xA7][x 0x82 0x88][x 0x91 0xA8][x 0x8E 0xAF][x 0x96 0xAA][x 0x80 0xFE][x 0x81 0x86][x 0x8C 0x86][x 0x80 0xE4][x 0x81 0xC0][x 0x81 0xEF][x 0x82 0x89][n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 120][x 0x82 0x9D][x 0x81 0x9C][x 0x80 0xDF][x 0x82 0x88][x 0x81 0xC0][x 0x81 0xEF][x 0x81 0x8D][x 0x81 0xC4][x 0x81 0xC4][x 0x81 0x89][x 0x92 0xB6][x 0x80 0xE2][x 0x80 0xF1][x 0x81 0x86][x 0x87 0xEA][x 0x81 0xA9][x 0x80 0xE9][x 0x81 0xA7][x 0x82 0x88][n][x 0x99 0xB5][x 0x81 0xA8][x 0x81 0x89][x 0x80 0xF5][x 0x81 0x84][x 0x80 0xED][x 0x81 0xAA][x 0x81 0xC0][x 0x81 0xEF][x 0x80 0x81][n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 121][x 0x82 0x9D][x 0x80 0xE0][x 0x82 0x88][x 0x81 0x85][x 0x81 0xA0][x 0x81 0xC0][x 0x81 0xEF][x 0x81 0x89][x 0x8D 0xBB][x 0x99 0xB3][x 0x81 0xA9][x 0x81 0x8C][x 0x81 0x8D][x 0x83 0xEB][x 0x94 0x9B][x 0x80 0xFE][x 0x80 0xEF][x 0x80 0xFE][x 0x80 0xE9][x 0x81 0xA7][x 0x82 0x88][n][x 0x8C 0xB8][x 0x96 0xDD][x 0x81 0x8C][x 0x8E 0xEF][x 0x81 0x8D][x 0x8C 0xB8][x 0x96 0xDD][x 0x81 0x85][x 0x8C 0xF6][x 0x81 0x81][x 0x81 0x84][x 0x99 0xAA][x 0x80 0xF5][x 0x80 0xE2][x 0x81 0xC0][x 0x81 0xEF][x 0x82 0x89][n][f 1 3 -1][f 1 1][e]

[msg MSG_071 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 12 -1 1][f 3 1 1 0 0 122]What happened to relying on you!?[n]Th-There better not be any monsters![n]You understand!?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 13 -1 1][f 3 1 1 0 0 123]We brought weapons, but I mean...[n]They're more for show![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 12 -1 1][f 4 9 22 3 5 0 5][f 3 1 1 0 0 124]We just got here! If it's so dangerous,[n]why don't you do something instead of[n]relying on us!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_072 [Teddie]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 125]Uh uh. No way. I've got no muscles.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 126]Oh! Oh! I'll give you guys moral[n]support from a safe distance![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 127]How's that sound?[n][f 1 3 -1][f 1 1][e]

[msg MSG_073]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> Can Teddie really not fight...?[n][f 1 3 -1][f 1 1][e]

[sel SEL_074]
[f 0 5 -258][f 2 1]Try touching Teddie[e]
[f 0 5 -258][f 2 1]Try pushing Teddie[e]
[f 0 5 -258][f 2 1]Try hitting Teddie[e]

[msg MSG_075 [Teddie]]
[f 0 5 -258][f 2 1][f 4 6 8 4 0 1][f 3 1 1 0 0 128]N-Noooo...[n][f 1 3 -1][f 1 1][e]

[msg MSG_076 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 14 -1 1][f 3 1 1 0 0 129]I-Is this thing for real!?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 13 -1 1][f 4 8 22 8][f 3 1 1 0 0 130]Ugh, this is so lame...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 15 -1 1][f 4 9 22 3 5 0 5][f 3 1 1 0 0 131]We swore to find the culprit and this[n]is all the backup we get...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_077 [Teddie]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 133]...Oh yeah. Can I ask you something?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 134]Who's this Saki-senpai person?[n]Someone you know?[n][f 1 3 -1][f 1 1][e]

[msg MSG_078 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 13 -1 1][f 3 1 1 0 0 135]......[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 136]That doesn't matter right now...[n][f 1 3 -1][f 1 1][e]

[msg MSG_079 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 0]Anyways, at least now we know Senpai[n]might have been thrown in here.[n][f 1 3 -1][f 1 1][e]

[msg MSG_080 [Teddie]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0][x 0x80 0xFB][x 0x81 0x8C][x 0x82 0x9F][x 0x8F 0xED][x 0x94 0xF1][x 0x80 0x82][x 0x81 0x81][x 0x81 0x84][x 0x82 0x88][x 0x81 0xBE][x 0x81 0xF0][x 0x80 0xFD][x 0x80 0xFF][x 0x81 0x8C][x 0x85 0xA0][x 0x80 0x9F][n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0][x 0x80 0xF1][x 0x81 0xAA][x 0x80 0xE9][x 0x81 0xA7][x 0x8A 0xC7][x 0x80 0xED][x 0x81 0x86][x 0x80 0xF1][x 0x82 0x88][x 0x84 0xC9][x 0x80 0xEA][x 0x90 0xDE][x 0x80 0xEA][x 0x80 0xF5][x 0x80 0xED][x 0x81 0x88][x 0x81 0x81][x 0x81 0x84][x 0x81 0xA9][x 0x82 0x89][n][x 0x8E 0xDB][x 0x93 0xD1][x 0x80 0xFD][x 0x81 0xA8][x 0x80 0xE0][x 0x81 0xA9][x 0x81 0xC0][x 0x81 0xEF][x 0x80 0xE9][x 0x80 0x9F][n][f 1 3 -1][f 1 1][e]

[msg MSG_081 [[x 0x85 0xB7][x 0x90 0xFD][x 0x99 0xA6][x 0x85 0xD1] ]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 0][x 0x80 0xE2][x 0x80 0xE2][x 0x80 0xE9][x 0x81 0xA7][x 0x82 0x88][x 0x81 0xA0][x 0x80 0xE4][x 0x8A 0xC7][x 0x80 0xED][x 0x80 0xFC][x 0x80 0x81][n][f 1 3 -1][f 1 1][e]

[msg MSG_082 [Teddie]]
[f 0 5 -258][f 2 1][f 4 6 8 4 0 1][f 3 1 1 0 0 139]W-Waaaait![n][f 1 3 -1][f 1 1][e]

[msg MSG_083 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 0][x 0x80 0xE0][x 0x80 0xE0][x 0x82 0x88][x 0x91 0x80][x 0x96 0xDD][x 0x81 0x88][x 0x82 0x9D][n][f 1 3 -1][f 1 1][e]

[msg MSG_084 [[x 0x81 0xC0][x 0x81 0xEF]]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 0][x 0x86 0x8D][x 0x80 0xE9][x 0x81 0x89][x 0x82 0x88][x 0x91 0xCE][x 0x80 0xE9][x 0x81 0x89][x 0x94 0xD8][x 0x80 0xE9][x 0x81 0xAA][x 0x81 0x84][x 0x80 0xE2][x 0x81 0xA9][x 0x81 0xA6][x 0x82 0x99][x 0x81 0x88][x 0x82 0x9D][n][x 0x80 0xFB][x 0x81 0xB1][x 0x81 0x88][x 0x87 0x9F][x 0x81 0xA0][x 0x82 0x88][x 0x80 0xFD][x 0x81 0x9C][x 0x81 0x89][x 0x80 0xF7][x 0x81 0xA9][x 0x80 0xEF][x 0x81 0x87][x 0x82 0x9D][n][f 1 3 -1][f 1 1][e]

[msg MSG_085 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 4 -1 1][f 3 1 1 0 0 93]*sigh* Hey, what should we do?[n][f 1 3 -1][f 1 1][e]

[msg MSG_086]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> You remember the words of the mysterious[n]old man who called himself Igor...[n][f 1 3 -1][f 1 1][e]

[msg MSG_087]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> As you put on the glasses, your vision[n]instantly becomes much clearer![n][f 1 3 -1][f 1 1][e]

[msg MSG_088 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 14 -1 1][f 3 1 1 0 0 112]Whoa![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 113]The difference is like night and day.[n]With these on, it's like the fog doesn't[n]exist.[n][f 1 3 -1][f 1 1][e]

[msg MSG_089]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0][x 0x80 0x9E][x 0x8C 0x9A][x 0x85 0xE5][x 0x81 0x8C][x 0x8A 0xA0][x 0x80 0xEA][x 0x81 0xA8][x 0x80 0xFE][x 0x80 0xEF][x 0x81 0x85][x 0x81 0x88][x 0x80 0xED][x 0x82 0x88][x 0x8E 0xDB][x 0x81 0x88][x 0x80 0xF5][x 0x80 0xE9][n][x 0x80 0x80][x 0x95 0xDD][x 0x9A 0xB2][x 0x86 0xD3][x 0x81 0xA0][x 0x99 0xA9][x 0x80 0xE6][x 0x81 0xA7][x 0x81 0xAA][x 0x81 0x84][x 0x80 0xE2][x 0x81 0xA9][x 0x87 0x9F][x 0x80 0xEA][x 0x80 0xF7][x 0x81 0xA9][x 0x82 0x9D][n][f 1 3 -1][f 1 1][e]

[msg MSG_090 [Mysterious bear]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 51]Aaaah... I get it...[n][f 1 3 -1][f 1 1][e]

[msg MSG_091 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 10 -1 1][f 3 1 1 0 0 137]Anyways, at least now we know Senpai[n]might have been thrown in here.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 138]Maybe we can find more information, too.[n]Let's get moving, [f 4 2].[n][f 1 3 -1][f 1 1][e]

[sel SEL_092]
[f 0 5 -258][f 2 1]"Hell no!"[e]
[f 0 5 -258][f 2 1]"Don't label us like that."[e]
[f 0 5 -258][f 2 1]"Shut up..."[e]

[sel SEL_093]
[f 0 5 -258][f 2 1]"Proof!?"[e]
[f 0 5 -258][f 2 1]"It doesn't work that way..."[e]
[f 0 5 -258][f 2 1]"Shut up."[e]

[sel SEL_094]
[f 0 5 -258][f 2 1]"Always been like this...?"[e]
[f 0 5 -258][f 2 1]"What do you mean?"[e]
[f 0 5 -258][f 2 1]"Run that by me again?"[e]

