[msg MSG_000]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> [f 4 3] has faced[n]his other self...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> He has obtained the facade used to[n]overcome life's hardships, the Persona[n][f 0 1 1]Izanagi[f 0 1 0]![n][f 1 3 -1][f 1 1][e]

[msg MSG_001 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 14 -1 1][f 3 1 1 0 0 1]Whoa... Wh-What was that!?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 2]Did I hear you say "Persona!?"[n]What was it--[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 9 2 28 5 18 5][f 3 1 1 0 0 3]I mean, what did you do!?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 4]Hey, you think I can do it too...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_002 [Teddie]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 5]Calm down, Yosuke. You're troubling[n]Sensei![n][f 1 3 -1][f 1 1][e]

[msg MSG_003 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 14 -1 1][f 3 1 1 0 0 6]S-Sensei...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_004 [Teddie]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 7]Gosh almighty! You're amazing, Sensei![n]I am one impressed bear![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 8]I can't believe you were hiding such an[n]amazing power! No wonder the Shadows[n]were scared of you![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 9 8 3 5 0 5][f 3 1 1 0 0 9]*gasp* Are you the one who's able[n]to bring people into this world?[n][f 1 3 -1][f 1 1][e]

[msg MSG_005 [Teddie]]
[f 0 5 -258][f 2 1][f 4 6 8 5 0 1][f 3 1 1 0 0 10]Hah! That's what I thought![n]This is really something.[n][f 1 3 -1][f 1 1][e]

[msg MSG_006 [Teddie]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 11]Don't you think so, Yosuke?[n][f 1 3 -1][f 1 1][e]

[msg MSG_007 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 12 -1 1][f 3 1 1 0 0 12]Dude, you call him Sensei and then don't[n]show me any respect!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_008 [Teddie]]
[f 0 5 -258][f 2 1][f 4 6 8 4 0 1][f 3 1 1 0 0 13]Sorry...[n][f 1 3 -1][f 1 1][e]

[msg MSG_009 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 11 -1 1][f 3 1 1 0 0 14]W-Well, your support wasn't bad, though.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 15]I gotta give you some credit for that.[n][f 1 3 -1][f 1 1][e]

[msg MSG_010 [Teddie]]
[f 0 5 -258][f 2 1][f 4 6 8 6 0 1][f 3 1 1 0 0 16]Huh? R-Really...? Heehee.[n][f 1 3 -1][f 1 1][e]

[msg MSG_011 [[x 0x85 0xB7][x 0x90 0xFD][x 0x99 0xA6][x 0x85 0xD1] ]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 0][x 0x80 0xF1][x 0x82 0x88][x 0x80 0xF1][x 0x80 0xE2][x 0x81 0x82][x 0x82 0x9D][n][f 1 3 -1][f 1 1][e]

[msg MSG_012 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 11 -1 1][f 3 1 1 0 0 17]All right, you two keep it up, and I[n]think we'll be fine from here on out.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 18]Now let's get back to the investigation![n][f 1 3 -1][f 1 1][e]

[msg MSG_013 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 10 -1 1][f 3 1 1 0 0 19]Man... I wonder what could have happened[n]to Senpai here.[n][f 1 3 -1][f 1 1][e]

[msg MSG_014]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> Voices begin to echo from somewhere...[n][f 1 3 -1][f 1 1][e]

[msg MSG_015 [Unknown voice]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 20]I wish Junes would go under...[n][f 1 3 -1][f 1 1][e]

[msg MSG_016 [Unknown voice]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 21]It's all because of that store...[n][f 1 3 -1][f 1 1][e]

[msg MSG_017 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 14 -1 1][f 3 1 1 0 0 22]Wh-What the...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_018 [Unknown voice]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 23]Oh, I heard that Konishi-san's daughter[n]is working there.[n][f 1 3 -1][f 1 1][e]

[msg MSG_019 [Unknown voice]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 24]Oh my... How could she, with her family's[n]business suffering like it is...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_020 [Unknown voice]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 25]I heard their sales have gone downhill[n]because of Junes.[n][f 1 3 -1][f 1 1][e]

[msg MSG_021 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 13 -1 1][f 3 1 1 0 0 26]S-Stop it...[n][f 1 3 -1][f 1 1][e]

[msg MSG_022 [Unknown voice]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 27]That poor father... to have his own[n]daughter working for the enemy.[n][f 1 3 -1][f 1 1][e]

[msg MSG_023 [Unknown voice]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 28]What a troublesome child...[n][f 1 3 -1][f 1 1][e]

[msg MSG_024 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 12 -1 1][f 3 1 1 0 0 29]Hey... Hey, Ted![n][f 1 3 -1][f 1 1][e]

[msg MSG_025 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 12 -1 1][f 3 1 1 0 0 30]You said that this place is reality for[n]those that are here, right!?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 31]So... does that mean this was Senpai's[n]reality when she wandered in here...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_026 [Teddie]]
[f 0 5 -258][f 2 1][f 4 6 8 1 0 1][f 3 1 1 0 0 32]I... only know about what's over here.[n][f 1 3 -1][f 1 1][e]

[msg MSG_027 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 10 -1 1][f 3 1 1 0 0 33]Fine...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 12 -1 1][f 3 1 1 0 0 34]Whatever's going on here... [n]We'll find out ourselves![n][f 1 3 -1][f 1 1][e]

