[msg MSG_000 [Sitting student]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 1]Talk about bad luck... The homeroom[n]teacher here is Morooka, isn't it?[n][f 1 3 -1][f 1 1][e]

[msg MSG_001 [Student's friend]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 2]Yeah, it's King Moron alright...[n]We get to enjoy his long-ass sermons[n]every day for a whole year...[n][f 1 3 -1][f 1 1][e]

[msg MSG_002 [Female student]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 3]Hey you guys, I heard there's going to[n]be a transfer student from the city in[n]this class.[n][f 1 3 -1][f 1 1][e]

[msg MSG_003 [Sitting student]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 4]Huh? Really? A guy or a girl?[n][f 1 3 -1][f 1 1][e]

[msg MSG_004 [Short-haired girl]]
[f 0 5 -258][f 2 1][f 4 6 3 1 -1 1][f 3 1 1 0 0 5]A transfer student from the city...[n]Just like you, huh, Yosuke?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 3 5 -1 1][f 3 1 1 0 0 6]...Huh? You look dead today.[n][f 1 3 -1][f 1 1][e]

[msg MSG_005 [Pained student]]
[f 0 5 -258][f 2 1][f 4 6 2 6 -1 1][f 3 1 1 0 0 7]Yeah, um... I don't wanna talk[n]about it...[n][f 1 3 -1][f 1 1][e]

[msg MSG_006 [Short-haired girl]]
[f 0 5 -258][f 2 1][f 4 6 3 1 -1 1][f 3 1 1 0 0 8]What's with him?[n][f 1 3 -1][f 1 1][e]

[msg MSG_007 [Black-haired girl]]
[f 0 5 -258][f 2 1][f 4 6 4 1 -1 1][f 3 1 1 0 0 9]Who knows?[n][f 1 3 -1][f 1 1][e]

[msg MSG_008 [Mr. Morooka]]
[f 0 5 -258][f 2 1][f 4 6 16 1 0 1][f 4 8 40 11][f 3 1 1 0 0 10]Awright, shut your traps![n][f 1 3 -1][f 1 1][e]

[msg MSG_009 [Mr. Morooka]]
[f 0 5 -258][f 2 1][f 4 6 16 1 0 1][f 3 1 1 0 0 14]Now I hate wasting my time, but I'd better[n]introduce this transfer student.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 15]This sad sack's been thrown from the big[n]city out to the middle of nowhere like[n]yesterday's garbage.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 9 40 3 5 0 5][f 3 1 1 0 0 16]And he's just as much of a loser here[n]as he was there, so you girls better not[n]get any ideas about hitting on him![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 17]Tell 'em your name, kid, and make[n]it quick.[n][f 1 3 -1][f 1 1][e]

[sel SEL_010]
[f 0 5 -258][f 2 1]"Nice to meet you all."[e]
[f 0 5 -258][f 2 1]"......"[e]
[f 0 5 -258][f 2 1]"...You calling me a loser?"[e]

[msg MSG_011 [Mr. Morooka]]
[f 0 5 -258][f 2 1][f 4 6 16 3 0 1][f 3 1 1 0 0 18]What's that look you're giving to that girl[n]back there by the window!? You thought[n]I wouldn't notice!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_012 [Mr. Morooka]]
[f 0 5 -258][f 2 1][f 4 6 16 1 0 1][f 3 1 1 0 0 19]Still going through a rebellious[n]phase, eh?[n][f 1 3 -1][f 1 1][e]

[msg MSG_013 [Mr. Morooka]]
[f 0 5 -258][f 2 1][f 4 6 16 3 0 1][f 3 1 1 0 0 20]Hrnh... That's it, you're on my shit list,[n]effective immediately.[n][f 1 3 -1][f 1 1][e]

[msg MSG_014 [Mr. Morooka]]
[f 0 5 -258][f 2 1][f 4 6 16 1 0 1][f 3 1 1 0 0 21]Now listen up![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 22]This town is miles away from your big[n]city of perverts and assholes, in more[n]ways than one.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 16 3 0 1][f 3 1 1 0 0 23]You better not even think of getting[n]involved with the girls here, let alone[n]abusing them![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 16 1 0 1][f 4 9 40 3 5 0 5][f 3 1 1 0 0 24]But what do I know... it's not like the[n]old days. Even here, kids grow up so[n]damn fast.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 25]Every time I turn my back, you're fooling[n]around on those damn phones, checking your[n]life-journals and your my-places...[n][f 1 3 -1][f 1 1][e]

[msg MSG_015]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> Mr. Morooka goes on and on...[n][f 1 3 -1][f 1 1][e]

[msg MSG_016 [Short-haired girl]]
[f 0 5 -258][f 2 1][f 4 6 3 1 -1 1][f 3 1 1 0 0 26]Excuse me! Is it okay if the transfer[n]student sits here?[n][f 1 3 -1][f 1 1][e]

[msg MSG_017 [Mr. Morooka]]
[f 0 5 -258][f 2 1][f 4 6 16 1 0 1][f 3 1 1 0 0 27]Huh? Yeah, sure. Ya hear that? Your seat's[n]over there.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 28]So hurry up and siddown already![n][f 1 3 -1][f 1 1][e]

[msg MSG_018 [Short-haired girl]]
[f 0 5 -258][f 2 1][f 4 6 3 1 -1 1][f 3 1 1 0 0 29]He's the worst, huh?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 3 4 -1 1][f 3 1 1 0 0 30]Rotten luck for you to get stuck in[n]this class... Well, we just have to[n]hang in there for a year.[n][f 1 3 -1][f 1 1][e]

[msg MSG_019 [Mr. Morooka]]
[f 0 5 -258][f 2 1][f 4 6 16 3 0 1][f 3 1 1 0 0 34]Shut your traps! I'm taking roll, and I[n]damn well expect you to respond in an[n]orderly manner![n][f 1 3 -1][f 1 1][e]

[msg MSG_020]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> Your life at this new school has begun.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> Will you be able to fit in here...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_021]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> You can hear people around you talking[n]about you...[n][f 1 3 -1][f 1 1][e]

[msg MSG_022 [Male student]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 31]Sucks to be the transfer student, ending[n]up in King Moron's class on the first[n]morning here...[n][f 1 3 -1][f 1 1][e]

[msg MSG_023 [Whiny student]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 32]Yeah, he won't think twice about[n]suspending you if you get on his[n]bad side.[n][f 1 3 -1][f 1 1][e]

[msg MSG_024 [Whiny student]]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 33]Then again, we're all in the same[n]boat...[n][f 1 3 -1][f 1 1][e]

[msg MSG_025 [Mr. Morooka]]
[f 0 5 -258][f 2 1][f 4 6 16 1 0 1][f 3 1 1 0 0 11]I'm Kinshiro Morooka, your homeroom[n]teacher from today forward![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 9 40 3 5 0 5][f 3 1 1 0 0 12]First things first! Just 'cause it's[n]spring doesn't mean you can swoon over[n]each other like love-struck baboons.[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 13]Long as I'm around, you students are[n]going to be pure as the driven snow![n][f 1 3 -1][f 1 1][e]

