[msg MSG_000]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> You can hear it raining outside...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> It's almost midnight...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> "Your soulmate appears if you look[n]into a TV on a rainy night..."[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> Could Chie's story be true...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_001]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> You can see the reflection of your[n]face in the TV's glass.[n][f 1 3 -1][f 1 1][e]

[msg MSG_002]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> Nothing else appears on the TV...[n][f 1 3 -1][f 1 1][e]

