[msg MSG_000 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 5 -1 1][f 3 1 1 0 0 1]Wow, this is huge! And... Holy crap, it's[n]expensive! Who buys something like this?[n][f 1 3 -1][f 1 1][e]

[msg MSG_001 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 2]I dunno... Rich folks?[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 3]Honestly, not many people shop for TVs[n]here. That's why we don't have clerks[n]around.[n][f 1 3 -1][f 1 1][e]

[msg MSG_002 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 1 -1 1][f 3 1 1 0 0 4]Huh... Not worth trying then, I guess.[n]Well, at least looking's free.[n][f 1 3 -1][f 1 1][e]

[msg MSG_003 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 5]...Nope, can't get in. Figures.[n][f 1 3 -1][f 1 1][e]

[msg MSG_004 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 2 -1 1][f 3 1 1 0 0 6]Haha, this proves it. It was all just[n]a dream.[n][f 1 3 -1][f 1 1][e]

[msg MSG_005 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 5 -1 1][f 3 1 1 0 0 7]Besides, these flat-screen TVs are so thin,[n]you'd just end up on the other side...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 9 -1 1][f 3 1 1 0 0 8]Argh, what am I saying!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_006 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 9]So, Chie. What kind of TV are you guys[n]in the market for?[n][f 1 3 -1][f 1 1][e]

[msg MSG_007 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 1 -1 1][f 3 1 1 0 0 10]They said they wanted one that's[n]cheap. You got any suggestions?[n][f 1 3 -1][f 1 1][e]

[msg MSG_008 [[x 0x85 0xB7][x 0x90 0xFD][x 0x99 0xA6][x 0x85 0xD1] ]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 0][x 0x80 0xFB][x 0x82 0x99][x 0x80 0xFE][x 0x81 0x88][x 0x80 0xE0][x 0x82 0x9D][n][f 1 3 -1][f 1 1][e]

[msg MSG_009 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 2 -1 1][f 3 1 1 0 0 11]Well, Miss, might I suggest this one[n]over here? It's the newest model, just[n]released this spring...[n][f 1 3 -1][f 1 1][e]

[msg MSG_010 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 5 -1 1][f 3 1 1 0 0 12]Wha--that's not cheap at all![n]There's way too many zeroes![n][f 1 3 -1][f 1 1][e]

[msg MSG_011 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 13]I should've asked what you meant by[n]"cheap" right off the bat.[n][f 1 3 -1][f 1 1][e]

[msg MSG_012 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 2 -1 1][f 3 1 1 0 0 14]You've got connections, right?[n]C'mon, hook me up![n][f 1 3 -1][f 1 1][e]

[msg MSG_013 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 9 -1 1][f 3 1 1 0 0 15]You know I can't do that...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 16]Hey, how about this one over here?[n]It's a display unit. It's a little[n]old, but...[n][f 1 3 -1][f 1 1][e]

[msg MSG_014]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> With a TV this big, you really might[n]be able to go inside...[n][f 1 3 -1][f 1 1][e]

[msg MSG_015 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 17]Oh yeah, [f 4 2], what kind[n]of TV do you--[n][f 1 3 -1][f 1 1][e]

[msg MSG_016 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 1 -1 1][f 3 1 1 0 0 18]Huh? Something wrong, Yosuke?[n][f 1 3 -1][f 1 1][e]

[msg MSG_017 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 8 -1 1][f 3 1 1 0 0 19]I-Is his arm... in the TV...?[n][f 1 3 -1][f 1 1][e]

[msg MSG_018 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 5 -1 1][f 3 1 1 0 0 20]Whoa...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 21]Uhhh... Is that some kinda... new model?[n]L-Like with a new function?[n][f 1 3 -1][f 1 1][e]

[msg MSG_019 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 8 -1 1][f 3 1 1 0 0 22]Hell no![n][f 1 3 -1][f 1 1][e]

[msg MSG_020 [[x 0x85 0xB7][x 0x90 0xFD][x 0x99 0xA6][x 0x85 0xD1] ]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 0][x 0x80 0xE0][x 0x80 0xFE][x 0x80 0xFE][x 0x80 0xFE][x 0x81 0x81][x 0x80 0x81][n][f 1 3 -1][f 1 1][e]

[msg MSG_021 [[x 0x99 0xCD][x 0x92 0x85][x 0x8F 0xEE][x 0x8C 0x8D] ]]
[f 0 5 -258][f 2 1][f 4 6 3 1 -1 1][f 3 1 1 0 0 0][x 0x81 0xA2][x 0x81 0x81][x 0x81 0x8F][x 0x82 0x88][x 0x98 0xA1][x 0x80 0xF6][x 0x81 0xA1][x 0x81 0x88][x 0x80 0xE2][x 0x81 0xB1][x 0x80 0xFE][x 0x82 0x9D][n][f 1 3 -1][f 1 1][e]

[msg MSG_022 [[x 0x99 0xCD][x 0x92 0x85][x 0x8F 0xEE][x 0x8C 0x8D] ]]
[f 0 5 -258][f 2 1][f 4 6 3 1 -1 1][f 3 1 1 0 0 0][x 0x80 0xE2][x 0x81 0x82][x 0x81 0x82][x 0x81 0x82][x 0x80 0x81][x 0x80 0x81][n][f 1 3 -1][f 1 1][e]

[msg MSG_023 [[x 0x85 0xB7][x 0x90 0xFD][x 0x99 0xA6][x 0x85 0xD1] ]]
[f 0 5 -258][f 2 1][f 4 6 2 1 -1 1][f 3 1 1 0 0 0][x 0x81 0x9C][x 0x80 0xF6][x 0x80 0xE9][x 0x81 0xA6][x 0x82 0x9D][n][f 1 3 -1][f 1 1][e]

[msg MSG_024 [[x 0x85 0xB7][x 0x90 0xFD][x 0x99 0xA6][x 0x85 0xD1] ]]
[f 0 5 -258][f 2 1][f 4 6 2 5 -1 1][f 3 1 1 0 0 0][x 0x81 0x82][x 0x80 0xE9][x 0x80 0xE8][x 0x90 0x93][x 0x80 0xFB][x 0x81 0xAA][x 0x82 0x88][x 0x81 0xEF][x 0x81 0xC9][x 0x81 0x85][x 0x80 0xF3][x 0x80 0xF3][x 0x81 0x81][x 0x81 0x84][x 0x81 0xB1][x 0x81 0x8C][x 0x80 0x81][x 0x80 0x9F][n][f 1 3 -1][f 1 1][e]

[msg MSG_025 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 8 -1 1][f 3 1 1 0 0 24]Oh man... This is for real... That's[n]some magic trick, man![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 4 6 2 5 -1 1][f 3 1 1 0 0 25]So how's it work, huh!? What's the[n]magician's secret!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_026]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> Both of them are staring at you,[n]astonished...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> You might be able to put in more than[n]just your arm...[n][f 1 3 -1][f 1 1][e]

[msg MSG_027 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 5 -1 1][f 3 1 1 0 0 26]H-Hey, don't do that! What're you doing!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_028]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> There's empty space inside...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> You tell them that.[n][f 1 3 -1][f 1 1][e]

[msg MSG_029 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 5 -1 1][f 3 1 1 0 0 28]Wh-What do you mean, "inside!?"[n][f 1 3 -1][f 1 1][e]

[msg MSG_030 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 5 -1 1][f 3 1 1 0 0 29]Wh-What do you mean, "empty space!?"[n][f 1 3 -1][f 1 1][e]

[msg MSG_031]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> It seems very spacious in here...[n][f 1 3 -1][f 1 1][e]

[msg MSG_032 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 8 -1 1][f 3 1 1 0 0 30]Wh-What do you mean, "spacious!?"[n][f 1 3 -1][f 1 1][e]

[msg MSG_033 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 5 -1 1][f 3 1 1 0 0 31]I mean, what's going on!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_034 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 6 -1 1][f 3 1 1 0 0 32]Holy crap... I-I think this is all too[n]much for my bladder...[n][f 1 3 -1][f 1 1][e]

[msg MSG_035 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 5 -1 1][f 3 1 1 0 0 33]What the--? Are you gonna pee your[n]pants!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_036 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 6 -1 1][f 3 1 1 0 0 34]I've been holding it in all day![n]I-I haven't had a chance to go...[n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 35]Aaarrgh! Can't... hold it... anymore...![n][f 1 3 -1][f 1 1][e]

[msg MSG_037 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 8 -1 1][f 3 1 1 0 0 36]Shit! Customers! They're coming![n][f 1 3 -1][f 1 1][e]

[msg MSG_038 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 5 -1 1][f 3 1 1 0 0 37]What!? But we've got a guy half stuck[n]in the TV here![n][f 1 3 -1][f 1 1][e]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 38]Wh-What're we gonna do!?[n][f 1 3 -1][f 1 1][e]

[msg MSG_039 [Yosuke]]
[f 0 5 -258][f 2 1][f 4 6 2 5 -1 1][f 3 1 1 0 0 39]What the!? W-Wai--WHOA!![n][f 1 2 70][e]

[msg MSG_040 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 5 -1 1][f 3 1 1 0 0 23]You gotta be kidding me... Did you really[n]stick your hand through the screen?[n][f 1 3 -1][f 1 1][e]

[msg MSG_041 [Chie]]
[f 0 5 -258][f 2 1][f 4 6 3 5 -1 1][f 3 1 1 0 0 27]Oh my God!![n][f 1 3 -1][f 1 1][e]

[msg MSG_042]
[f 0 5 -258][f 2 1][f 3 1 1 0 0 0]> Junes, Electronics department...[n][f 1 3 -1][f 1 1][e]

